using System.Collections;
using System.Collections.Generic;
using UnityEditor;
using UnityEngine;
using System.IO;
using System.Reflection;
using System;

public static class AttoAccessBuilder
{

    static string coreClassName = "Core";

    const string defaultCoreName = "Core";

    [InitializeOnLoadMethod]
    public static void OnInitialize()
    {
        if (EditorApplication.isPlaying) { return; }
        EditorApplication.update += Update;
    }

    private static void Update()
    {
        if (EditorApplication.isPlayingOrWillChangePlaymode && !EditorApplication.isPlaying)
        {
            ReloadServices();
        }
    }

    [MenuItem("Tools/ReloadServices")]
    public static void ReloadServices()
    {
        GetCoreName();
        var bindingsList = GetBindingsList();
        WriteAccessFile(bindingsList);
    }

    private static void GetCoreName()
    {
        var settings = new AttoSettingsProvider();
        var customCoreName = settings.Current.coreName;
        if (!string.IsNullOrEmpty(customCoreName))
        {
            coreClassName = customCoreName;
        }
        else
        {
            coreClassName = defaultCoreName;
        }
    }

    public static void LogReadyServices()
    {
        var bindingsList = GetBindingsList();
        foreach (var binding in bindingsList)
        {
            Debug.Log(binding.providerClass + " -> IMPLEMENTS -> " + binding.interfaceName + " AS A." + binding.accessDescriptor);
        }
        Debug.Log("Loaded services: " + bindingsList.Count);
    }

    static List<ServiceAtributeBinding> GetBindingsList()
    {
        List<ServiceAtributeBinding> results = new List<ServiceAtributeBinding>();

        foreach (Assembly assembly in AppDomain.CurrentDomain.GetAssemblies())
        {
            foreach (var type in assembly.GetTypes())
            {
                var binding = GetBindingFromType(type);
                if (binding != null && binding.IsEnabled)
                {
                    results.Add(binding);
                }
            }
        }
        
        return results;
    }

    static ServiceAtributeBinding GetBindingFromType(Type type)
    {
        ServiceAtributeBinding result = new ServiceAtributeBinding();

        result.providerClass = type;

        var attributes = type.GetCustomAttributes(typeof(BindService), true);
        if (attributes.Length == 1)
        {
            var bindAttribute = (BindService)attributes[0];
            //result.accessDescriptor = bindAttribute.accessDescriptor;
            result.serviceMode = bindAttribute.serviceMode;
            result.serviceCaching = bindAttribute.serviceCaching;
        }

        var interfaces = type.GetInterfaces();
        if (interfaces.Length == 1)
        {
            result.interfaceName = interfaces[0].ToString();
        }

        if (!result.IsValid)
        {
            result = null;
        }

        return result;
    }

    static void WriteAccessFile(List<ServiceAtributeBinding> bindings)
    {
        var fileContents = "";
        fileContents += WriteClassHeader(bindings);

        foreach (var binding in bindings)
        {
            fileContents += WriteAccessDescriptor(binding);
        }

        fileContents += WriteClassFooter();
        
        string path = Application.dataPath + "/AttoAccess.cs";
        File.WriteAllText(path, fileContents);
        AssetDatabase.Refresh();
    }


    static string WriteClassHeader(List<ServiceAtributeBinding> bindings)
    {
        var result = "//This class is auto-generated by the Atto framework. You shouldn't edit it.\n\n\n";
        result += "using UnityEngine;\n\n public static partial class "+coreClassName+"\n{\n";
        result += "\t[RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.BeforeSceneLoad)]\n";
        result += "\tpublic static void BindCommonServices()\n\t{\n";
        result += "\t\tAtto.Bind<ISettingsService, AttoSettingsProvider>();\n";
        result += "\t\tif (Settings.Current.autoBindCommonServices)\n{\n";

        foreach (var binding in bindings)
        {
            result += "\t\t\tAtto.Bind<" + binding.interfaceName + "," + binding.providerClass.Name + ">();\n";
        }

        result += "\t\t}\n\t}\n\n";
        return result;
    }

    static string WriteAccessDescriptor(ServiceAtributeBinding binding)
    {
        string prefix = "";
        string sufix = "";
        if (!binding.IsVisible)
        {
            prefix = "/*This service is hidden from API use, use Atto.Get<IService>() to access it from other services.\n";
        }
        string header = "\tpublic static ";
        string type = binding.interfaceName + " " + binding.accessDescriptor;
        string body = " { get { ";
        if (binding.serviceCaching == ServiceCaching.Dynamic)
        {
            body += "return Atto.Get<" + binding.interfaceName + ">();";
            body += " }\n";
            body += "}\n";
        }
        else if (binding.serviceCaching == ServiceCaching.Static)
        {
            string privateAccessDescriptor = binding.accessDescriptor + "_ ";
            body += "if (" + privateAccessDescriptor + "== null) {";
            body += privateAccessDescriptor + "= Atto.Get<" + binding.interfaceName + ">();} return " + privateAccessDescriptor + ";";
            body += " } }\n";
            body += "\tstatic " + binding.interfaceName + " " + privateAccessDescriptor + ";";
        }
        else
        {
            Debug.LogError("Undefined caching service for " + binding.providerClass.ToString());
        }
        if (!binding.IsVisible)
        {
            sufix = "\n*/";
        }

        string result = prefix + header + type + body + sufix + "\n\n";
        return result;
    }

    static string WriteClassFooter()
    {
        return "}";
    }

    class ServiceAtributeBinding
    {
        public Type providerClass;
        public ServiceMode serviceMode;
        public ServiceCaching serviceCaching;
        public string accessDescriptor { get { return interfaceName.Substring(1, interfaceName.Length-1).Replace("Service", ""); } }
        public string interfaceName;

        public bool IsValid { get { return interfaceName != "" && providerClass != null && serviceCaching != ServiceCaching.Undefined && serviceMode != ServiceMode.Undefined; } }
        public bool IsEnabled { get { return serviceMode != ServiceMode.Disabled; } }
        public bool IsVisible { get { return serviceMode != ServiceMode.Hidden; } }

        public override string ToString()
        {
            string result = "";
            if (providerClass != null)
            {
                result += "[Binding] " + providerClass.Name;
            }
            else
            {
                result += "[Binding] " + "UNKNOWN";
            }
            result += " provides " + interfaceName;
            result += " as " + coreClassName;
            result += "." + accessDescriptor;
            result += " with [" + serviceMode.ToString();
            result += ", " + serviceCaching.ToString() + "]";

            return result;
        }
    }

}
